In [1]:
import os

In [ ]:
from google.colab import files
uploaded = files.upload()


KeyboardInterrupt: 

In [2]:
import pandas as pd
import numpy as np
# Use full path to your file
path = '/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv'
df = pd.read_csv(path)

df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df["review"]=df["review"].str.lower()

In [4]:
df["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

**remove html tag**

In [5]:
import re

def remove_html_tags(text):
    pattern = re.compile(r'<.*?>')  # Correct regex for HTML tags
    return pattern.sub('', text)

text = "<html><p>my name is sourav</p></html>"
print(remove_html_tags(text))


my name is sourav


In [6]:
df["review"]=df['review'].apply(remove_html_tags)

In [7]:
import re

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

text = "Visit https://example.com or http://test.com or www.google.com for info."
print(remove_url(text))


Visit  or  or  for info.


**punctuation**

In [8]:
import string,time
string.punctuation
exclude =string .punctuation

In [9]:
import string
import time

def remove_punc(text):
    for char in exclude:              #it specifically holds every standard punctuation mark.
        text = text.replace(char, '')
    return text

exclude = set(string.punctuation)
text = 'string. With. Punctuation?'
start = time.time()

print(remove_punc(text))
time1 = time.time() - start
print(time1 * 50000)

string With Punctuation
6.186962127685547


## **2nd way of removing punctuation**

In [10]:
import string
import time

def remove_punc1(text3):
    return text3.translate(str.maketrans('','', ''.join(exclude)))
text3 = 'string. With. Punctuation?'
exclude = set(string.punctuation)
start=time.time()
remove_punc1(text3)
print(remove_punc1(text3))
time1 = time.time() - start
print(time1 * 50000)

string With Punctuation
16.772747039794922


# **slang**

In [11]:
slang_dict = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "A3": "Anytime, Anywhere, Anyplace",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "B4": "Before",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FWIW": "For What It's Worth",
    "FYI": "For Your Information",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GN": "Good Night",
    "GMTA": "Great Minds Think Alike",
    "GR8": "Great!",
    "G9": "Genius",
    "IC": "I See",
    "ICQ": "I Seek You (also a chat program)",
    "ILU": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "KISS": "Keep It Simple, Stupid",
    "LDR": "Long Distance Relationship",
    "LMAO": "Laugh My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "L8R": "Later",
    "MTE": "My Thoughts Exactly",
    "M8": "Mate",
    "NRN": "No Reply Necessary",
    "OIC": "Oh I See",
    "PITA": "Pain In The A**",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "QPSA?": "Que Pasa?",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "SK8": "Skate",
    "STATS": "Your Sex and Age",
    "ASL": "Age, Sex, Location",
    "THX": "Thank You",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "WB": "Welcome Back",
    "WTF": "What The F...",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "W8": "Wait...",
    "7K": "Sick:-D Laughter",
    "TFW": "That Feeling When",
    "MFW": "My Face When",
    "MRW": "My Reaction When",
    "IFYP": "I Feel Your Pain",
    "TNTL": "Trying Not To Laugh",
    "JK": "Just Kidding",
    "IDC": "I Don’t Care",
    "ILY": "I Love You",
    "IMU": "I Miss You",
    "ADIH": "Another Day In Hell",
    "ZZZ": "Sleeping, Bored, Tired",
    "WYWH": "Wish You Were Here",
    "TIME": "Tears In My Eyes",
    "BAE": "Before Anyone Else",
    "FIMH": "Forever In My Heart",
    "BSAAW": "Big Smile And A Wink",
    "BWL": "Bursting With Laughter",
    "BFF": "Best Friends Forever",
    "CSL": "Can’t Stop Laughing",
    "SMH": "Shaking My Head",
    "IDK": "I Don't Know",
    "TBH": "To Be Honest",
    "RN": "Right Now",
    "DM": "Direct Message",
    "DMs": "Direct Messages",
    "ICYMI": "In Case You Missed It",
    "NSFW": "Not Safe For Work",
    "NSFL": "Not Safe For Life",
    "GTG": "Got To Go",
    "TMI": "Too Much Information",
    "OMG": "Oh My God",
    "OMFG": "Oh My F***ing God",
    "YOLO": "You Only Live Once",
    "FOMO": "Fear Of Missing Out",
    "FTW": "For The Win",
    "BRUH": "Bro / Are you serious?",
    "IDGAF": "I Don’t Give A F***",
    "IDC": "I Don’t Care",
    "NVM": "Nevermind",
    "HBU": "How About You?",
    "HMU": "Hit Me Up",
    "TTYS": "Talk To You Soon",
    "TBF": "To Be Fair",
    "RN": "Right Now",
    "TIL": "Today I Learned",
    "ILYSM": "I Love You So Much",
    "IIRC": "If I Recall Correctly",
    "WDYM": "What Do You Mean?",
    "WYD": "What You Doing?",
    "WBU": "What About You?",
    "OMW": "On My Way",
    "NOYB": "None Of Your Business",
    "LMS": "Like My Status",
    "BAF": "Bring A Friend",
    "SUS": "Suspicious / Suspect",
    "FYP": "For You Page (TikTok)",
    "CEO": "Used as a joke for 'master of something'",
    "G2G": "Got To Go",
    "OTP": "One True Pairing (ship/fandom slang)",
    "FR": "For Real",
    "FRFR": "For Real, For Real",
    "CAP": "Lie or false",
    "NO CAP": "No lie / For real",
    "SLAY": "Did something amazing / nailed it",
    "GOAT": "Greatest Of All Time",
    "BOP": "Good song / catchy song",
    "SIMP": "Someone who does too much for someone they like",
    "W": "Win",
    "L": "Loss",
    "SZN": "Season",
    "RT": "Retweet / Agree"


}


In [12]:
def chat_conversion(text):
  slang_dict = {
      "AFAIK": "As Far As I Know",
      "AFK": "Away From Keyboard",
      "ASAP": "As Soon As Possible",
      "ATK": "At The Keyboard",
      "ATM": "At The Moment",
      "A3": "Anytime, Anywhere, Anyplace",
      "BAK": "Back At Keyboard",
      "BBL": "Be Back Later",
      "BBS": "Be Back Soon",
      "BFN": "Bye For Now",
      "B4N": "Bye For Now",
      "BRB": "Be Right Back",
      "BRT": "Be Right There",
      "BTW": "By The Way",
      "B4": "Before",
      "CU": "See You",
      "CUL8R": "See You Later",
      "CYA": "See You",
      "FAQ": "Frequently Asked Questions",
      "FC": "Fingers Crossed",
      "FWIW": "For What It's Worth",
      "FYI": "For Your Information",
      "GAL": "Get A Life",
      "GG": "Good Game",
      "GN": "Good Night",
      "GMTA": "Great Minds Think Alike",
      "GR8": "Great!",
      "G9": "Genius",
      "IC": "I See",
      "ICQ": "I Seek You (also a chat program)",
      "ILU": "I Love You",
      "IMHO": "In My Honest/Humble Opinion",
      "IMO": "In My Opinion",
      "IOW": "In Other Words",
      "IRL": "In Real Life",
      "KISS": "Keep It Simple, Stupid",
      "LDR": "Long Distance Relationship",
      "LMAO": "Laugh My A** Off",
      "LOL": "Laughing Out Loud",
      "LTNS": "Long Time No See",
      "L8R": "Later",
      "MTE": "My Thoughts Exactly",
      "M8": "Mate",
      "NRN": "No Reply Necessary",
      "OIC": "Oh I See",
      "PITA": "Pain In The A**",
      "PRT": "Party",
      "PRW": "Parents Are Watching",
      "QPSA?": "Que Pasa?",
      "ROFL": "Rolling On The Floor Laughing",
      "ROFLOL": "Rolling On The Floor Laughing Out Loud",
      "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
      "SK8": "Skate",
      "STATS": "Your Sex and Age",
      "ASL": "Age, Sex, Location",
      "THX": "Thank You",
      "TTFN": "Ta-Ta For Now!",
      "TTYL": "Talk To You Later",
      "U": "You",
      "U2": "You Too",
      "U4E": "Yours For Ever",
      "WB": "Welcome Back",
      "WTF": "What The F...",
      "WTG": "Way To Go!",
      "WUF": "Where Are You From?",
      "W8": "Wait...",
      "7K": "Sick:-D Laughter",
      "TFW": "That Feeling When",
      "MFW": "My Face When",
      "MRW": "My Reaction When",
      "IFYP": "I Feel Your Pain",
      "TNTL": "Trying Not To Laugh",
      "JK": "Just Kidding",
      "IDC": "I Don’t Care",
      "ILY": "I Love You",
      "IMU": "I Miss You",
      "ADIH": "Another Day In Hell",
      "ZZZ": "Sleeping, Bored, Tired",
      "WYWH": "Wish You Were Here",
      "TIME": "Tears In My Eyes",
      "BAE": "Before Anyone Else",
      "FIMH": "Forever In My Heart",
      "BSAAW": "Big Smile And A Wink",
      "BWL": "Bursting With Laughter",
      "BFF": "Best Friends Forever",
      "CSL": "Can’t Stop Laughing",
      "SMH": "Shaking My Head",
      "IDK": "I Don't Know",
      "TBH": "To Be Honest",
      "RN": "Right Now",
      "DM": "Direct Message",
      "DMs": "Direct Messages",
      "ICYMI": "In Case You Missed It",
      "NSFW": "Not Safe For Work",
      "NSFL": "Not Safe For Life",
      "GTG": "Got To Go",
      "TMI": "Too Much Information",
      "OMG": "Oh My God",
      "OMFG": "Oh My F***ing God",
      "YOLO": "You Only Live Once",
      "FOMO": "Fear Of Missing Out",
      "FTW": "For The Win",
      "BRUH": "Bro / Are you serious?",
      "IDGAF": "I Don’t Give A F***",
      "IDC": "I Don’t Care",
      "NVM": "Nevermind",
      "HBU": "How About You?",
      "HMU": "Hit Me Up",
      "TTYS": "Talk To You Soon",
      "TBF": "To Be Fair",
      "RN": "Right Now",
      "TIL": "Today I Learned",
      "ILYSM": "I Love You So Much",
      "IIRC": "If I Recall Correctly",
      "WDYM": "What Do You Mean?",
      "WYD": "What You Doing?",
      "WBU": "What About You?",
      "OMW": "On My Way",
      "NOYB": "None Of Your Business",
      "LMS": "Like My Status",
      "BAF": "Bring A Friend",
      "SUS": "Suspicious / Suspect",
      "FYP": "For You Page (TikTok)",
      "CEO": "Used as a joke for 'master of something'",
      "G2G": "Got To Go",
      "OTP": "One True Pairing (ship/fandom slang)",
      "FR": "For Real",
      "FRFR": "For Real, For Real",
      "CAP": "Lie or false",
      "NO CAP": "No lie / For real",
      "SLAY": "Did something amazing / nailed it",
      "GOAT": "Greatest Of All Time",
      "BOP": "Good song / catchy song",
      "SIMP": "Someone who does too much for someone they like",
      "W": "Win",
      "L": "Loss",
      "SZN": "Season",
      "RT": "Retweet / Agree"
  }
  new_text=[];
  for w in text.split():
    if w.upper() in slang_dict:
      new_text.append(slang_dict[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)
chat_conversion("OMG where are you ")

'Oh My God where are you'

spelling mistake

In [13]:
from textblob import TextBlob
incorrect_text='ceeertain several saaame'
textblob=TextBlob(incorrect_text)
textblob.correct().string

'certain several same'

remove stop **words**

In [14]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [15]:
from nltk.corpus import stopwords
# Get the set of English stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
  new_text = []
  # Split the text into words
  for word in text.split():
    # Check if the word is not in the set of stopwords
    if word not in stop_words:
      # Append the word to the new list
      new_text.append(word)
  # Join the words back into a string
  return " ".join(new_text)

# Example usage:
text = "i am in my oldest house in dhaka named sarder villa"
print(remove_stopwords(text))

oldest house dhaka named sarder villa


In [16]:
df['review'].apply(remove_stopwords)

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production. filming technique...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy (jake) thi...
4        petter mattei's "love time money" visually stu...
                               ...                        
49995    thought movie right good job. creative origina...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art, fans ex...
Name: review, Length: 50000, dtype: object

handeling emoji

# `remove **emoji**`

In [18]:
%pip install emoji

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 10.7 MB/s eta 0:00:00


In [19]:
import emoji

def remove_emoji(text):
  # Use the demojize function from the emoji library to replace emojis with their text representation
  return emoji.demojize(text)

# Example usage:
remove_emoji("game is on 🔥🔥")

'game is on :fire::fire:'

In [21]:
import emoji
print(emoji.demojize('game is on 🔥🔥'))

game is on :fire::fire:


tokenization

In [22]:
sent1="i am going to delhi"
sent1.split()

['i', 'am', 'going', 'to', 'delhi']

In [23]:
sent2="I am going to Delhi.I  will stay here for three days "
sent2.split(".")

['I am going to Delhi', 'I  will stay here for three days ']

In [24]:
import re
sent3="i am going to delhi!"
tokens=re.findall("['\w']+",sent3)

In [25]:
tokens

['i', 'am', 'going', 'to', 'delhi']

NLTK library

In [26]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [27]:
from nltk.tokenize import word_tokenize

sent1="I am going to visit Delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'Delhi', '!']

**spacy library**

In [28]:
sent1="I am going to visit delhi!"
sent2="I am going to delhi!"
sent3="I am going to delhi!"

import spacy
nlp=spacy.load('en_core_web_sm')
doc1=nlp(sent1)
doc2=nlp(sent2)
doc3=nlp(sent3)
for  token in doc1:
  print(token)


I
am
going
to
visit
delhi
!


# **stemming**

In [29]:
from nltk.stem.porter import PorterStemmer
pst=PorterStemmer()
def stem_words(text):
  return "".join([pst.stem(word) for word in text.split()])
sample="walk walks walking walked"
stem_words(sample)

'walkwalkwalkwalk'

# lemmatization

In [30]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [31]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer=WordNetLemmatizer()
sentence="He was running  and eating at the sametime.He had  a bad habit of swimming after playing  toy in the sun "
punctuations="?:!.,;"
sentence_words=nltk.word_tokenize(sentence)
for word in sentence_words:
  if word in punctuations:
    sentence_words.remove(word)
sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
  print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word)))


Word                Lemma               
He                  He                  
was                 wa                  
running             running             
and                 and                 
eating              eating              
at                  at                  
the                 the                 
sametime.He         sametime.He         
had                 had                 
a                   a                   
bad                 bad                 
habit               habit               
of                  of                  
swimming            swimming            
after               after               
playing             playing             
toy                 toy                 
in                  in                  
the                 the                 
sun                 sun                 


# **text representation/vectorization:from text  convert it to  number**

# **while one is converting from text to no then i have to conscious that (it should cover all the semantic  meaning )**
# ** its ways are**:(ohe,bag of words,ngrams,tf,idf,custom features )

each and every review in dataset is a **document** and their summation is **corpus.**, and each word of document is called **word** and each unique word  is  a **vocabulary** .


d1="people watch campusx"

d2="campusx watch campusx"

d3="people write comment"

d4="campusx write comment"
summation of all these  is called corpus . and

vocabulary=people watch campusx write comment.each of these words(unique) are called vocabulary
/////////////////////////
ohe->semantic meaning capture kore na .






bag of words :semantic meaning capture kore tobe kom.aita mainly text classification a use hoy.
output = target (what you want the model to learn to predict)
You need the "output" column because it gives the ground truth label that your model learns from.



---




In [32]:
import numpy as np
import pandas as pd
# Create a pandas DataFrame with 'text' and 'output' columns
df1 = pd.DataFrame({
    "text": ["people watch campusx", "campusx watch campusx", "people write comment", "campusx write comment"],
    "output": [1, 1, 0, 0]
})
# Display the DataFrame
display(df1)

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [33]:
from sklearn .feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df1['text'])
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df1['text'])#train korlam model ke
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [35]:
# proti ta bow  er vocabulary er word er  sathe map kore then sob gula individual doc ke  check kora hoy ..kothay 1 ar kothay 0
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


oov er baire theke asa owrd bad dibe and jara ache tader niyei kaj hobe j tara kotobar asche

In [36]:
cv.transform(["campusx watch & write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])


**bag of ngrams:rather than taking  a single word in vocabulary,i take  a group of words in vocabulary  as  a result semantic meaning valo capture hoy**

# **BAG OF NGRAMS**: aita seamntic meaning capture korte pare valo vabe

In [37]:
#bigrams
import numpy as np
import pandas  as pd
df=pd.DataFrame({
                 "text": ["people watch campusx",
                 "campusx watch campusx",
                 "people write comment",
                 "campusx write comment"],
               "output":[1,1,0,0]
})
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


aita semantic meaning capture  kore.aita te token beshi hoy.(unigram er token< bigram er token)

tf idf eta word er importance basis e weight  apply kora hoy. ja (ohe,bag of words kore  na ) .kono word jodi akta doc e onekbar ase and ful corpus e kom ase tahole aita hoy.(tokhon weight er gurutto bojha jay)

tf=(no of occurances of term t in doc d)/(no  of terms in doc d)
idf=log{(total no of docs in corpus)/(no of docs with term t in that )}

In [38]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
import pandas as pd

# Assuming df DataFrame is already defined and contains a 'text' column
# (based on previous cells in the notebook)

# Step 1: Use CountVectorizer to get token counts
cv = CountVectorizer()
bow_matrix = cv.fit_transform(df['text'])

# Step 2: Use TfidfTransformer to compute TF-IDF from the count matrix
tfidf = TfidfTransformer()
tfidf_matrix = tfidf.fit_transform(bow_matrix)

# Print the IDF values
print("IDF values:", tfidf.idf_)

# Print the feature names (vocabulary) from the CountVectorizer
print("Feature names:", cv.get_feature_names_out())

# Print the TF-IDF matrix
print("TF-IDF matrix:\n", tfidf_matrix.toarray())

IDF values: [1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
Feature names: ['campusx' 'comment' 'people' 'watch' 'write']
TF-IDF matrix:
 [[0.49681612 0.         0.61366674 0.61366674 0.        ]
 [0.8508161  0.         0.         0.52546357 0.        ]
 [0.         0.57735027 0.57735027 0.         0.57735027]
 [0.49681612 0.61366674 0.         0.         0.61366674]]
